:Author: lmarcal
:Email: {AuthorEmail}
:Date: 05/07/2023
:Revision: version1.0
:License: Public Domain

= Project: {sunlight}


== Step 1: Installation
To use this project is necessary install the SunPosition, RTClib and FastLED libraries.

For example:

1. Just install in your arduino device the libraries and upload the .ino archive.
2. Connect the correctly components to run the project.
3. Make your own sun!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram electrical.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board/device.

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sunlight.ino       => main Arduino file
  ├── elecrical.png      => an image of the required schematics 
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact lmarcal https://id.arduino.cc/lmarcal
also you can send an mail to lmarcal789@gmail.com

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 330 Resistor*  | 330QBK-ND   | 1
| L1 | WS2812B LED    | WS2812B     | 1 
| A1 | Arduino Uno R3 | A000066     | 1
| C1 | RTC 3231       | DS3231RTC   | 1
|===

* - each 25 leds on the strip raise 1A in consume


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
